-- [[ GENERATED WITH InfernoHub/Scriptify STUDIO PLUGIN ]] --
-- Scriptify Version: 1.0

--

-- Create objects
local parent = nil;
local objects = {
	["Instance0"] = Instance.new("ScreenGui"); -- VSCode
	["Instance1"] = Instance.new("TextButton"); -- Window
	["Instance2"] = Instance.new("Frame"); -- TopbarZone
	["Instance3"] = Instance.new("ImageLabel"); -- Icon
	["Instance4"] = Instance.new("UIAspectRatioConstraint"); -- UIAspectRatioConstraint
	["Instance5"] = Instance.new("TextLabel"); -- Title
	["Instance6"] = Instance.new("Frame"); -- Separator
	["Instance7"] = Instance.new("Frame"); -- Buttons
	["Instance8"] = Instance.new("UIListLayout"); -- UIListLayout
	["Instance9"] = Instance.new("TextButton"); -- Minimize
	["Instance10"] = Instance.new("UIPadding"); -- UIPadding
	["Instance11"] = Instance.new("TextButton"); -- Maximize
	["Instance12"] = Instance.new("UIPadding"); -- UIPadding
	["Instance13"] = Instance.new("TextButton"); -- Close
	["Instance14"] = Instance.new("UIPadding"); -- UIPadding
	["Instance15"] = Instance.new("UIStroke"); -- UIStroke
	["Instance16"] = Instance.new("Frame"); -- Contents
	["Instance17"] = Instance.new("Frame"); -- Top
	["Instance18"] = Instance.new("ScrollingFrame"); -- Tabs
	["Instance19"] = Instance.new("TextButton"); -- Tab
	["Instance20"] = Instance.new("Frame"); -- LeftSeparator
	["Instance21"] = Instance.new("Frame"); -- Selected
	["Instance22"] = Instance.new("ImageLabel"); -- Icon
	["Instance23"] = Instance.new("UIAspectRatioConstraint"); -- UIAspectRatioConstraint
	["Instance24"] = Instance.new("Frame"); -- RightSeparator
	["Instance25"] = Instance.new("Frame"); -- NameHolder
	["Instance26"] = Instance.new("TextLabel"); -- Label
	["Instance27"] = Instance.new("TextButton"); -- Close
	["Instance28"] = Instance.new("UIAspectRatioConstraint"); -- UIAspectRatioConstraint
	["Instance29"] = Instance.new("UIPadding"); -- UIPadding
	["Instance30"] = Instance.new("UIListLayout"); -- UIListLayout
	["Instance31"] = Instance.new("Frame"); -- Separator
	["Instance32"] = Instance.new("Frame"); -- Buttons
	["Instance33"] = Instance.new("UIListLayout"); -- UIListLayout
	["Instance34"] = Instance.new("TextButton"); -- Clear
	["Instance35"] = Instance.new("ImageLabel"); -- ImageLabel
	["Instance36"] = Instance.new("TextButton"); -- Execute
	["Instance37"] = Instance.new("ImageLabel"); -- ImageLabel
	["Instance38"] = Instance.new("TextBox"); -- CodeEditor
	["Instance39"] = Instance.new("Frame"); -- Scripts
	["Instance40"] = Instance.new("Frame"); -- Separator
	["Instance41"] = Instance.new("UIAspectRatioConstraint"); -- UIAspectRatioConstraint
	["Instance42"] = Instance.new("LocalScript"); -- Editor
};

do -- Set properties
	objects["Instance0"]["Enabled"] = true;
	objects["Instance0"]["ScreenInsets"] = Enum.ScreenInsets.None;
	objects["Instance0"]["SafeAreaCompatibility"] = Enum.SafeAreaCompatibility.None;
	objects["Instance0"]["ClipToDeviceSafeArea"] = true;
	objects["Instance0"]["Parent"] = parent;
	objects["Instance0"]["IgnoreGuiInset"] = true;
	objects["Instance0"]["Name"] = "VSCode";
	objects["Instance0"]["DisplayOrder"] = 2147483647;

	objects["Instance1"]["Visible"] = true;
	objects["Instance1"]["FontSize"] = Enum.FontSize.Size14;
	objects["Instance1"]["TextDirection"] = Enum.TextDirection.Auto;
	objects["Instance1"]["Active"] = true;
	objects["Instance1"]["TextStrokeTransparency"] = 1;
	objects["Instance1"]["TextTruncate"] = Enum.TextTruncate.None;
	objects["Instance1"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance1"]["ZIndex"] = 1;
	objects["Instance1"]["BorderSizePixel"] = 0;
	objects["Instance1"]["Draggable"] = false;
	objects["Instance1"]["RichText"] = false;
	objects["Instance1"]["Modal"] = false;
	objects["Instance1"]["AutoButtonColor"] = false;
	objects["Instance1"]["Transparency"] = 0;
	objects["Instance1"]["SelectionOrder"] = 0;
	objects["Instance1"]["TextYAlignment"] = Enum.TextYAlignment.Center;
	objects["Instance1"]["TextScaled"] = false;
	objects["Instance1"]["TextWrap"] = false;
	objects["Instance1"]["FontFace"] = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal, false);
	objects["Instance1"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance1"]["Parent"] = objects["Instance0"];
	objects["Instance1"]["AnchorPoint"] = Vector2.new(0.5, 0.5);
	objects["Instance1"]["Style"] = Enum.ButtonStyle.Custom;
	objects["Instance1"]["Position"] = UDim2.new(0.5, 0, 0.5, 0);
	objects["Instance1"]["BackgroundColor3"] = Color3.new(0.121569, 0.121569, 0.121569);
	objects["Instance1"]["Selected"] = false;
	objects["Instance1"]["TextSize"] = 14;
	objects["Instance1"]["Size"] = UDim2.new(0.5, 0, 0.5, 0);
	objects["Instance1"]["BackgroundTransparency"] = 0;
	objects["Instance1"]["TextWrapped"] = false;
	objects["Instance1"]["ClipsDescendants"] = true;
	objects["Instance1"]["TextColor3"] = Color3.new(0, 0, 0);
	objects["Instance1"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance1"]["Text"] = "";
	objects["Instance1"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance1"]["LayoutOrder"] = 0;
	objects["Instance1"]["Rotation"] = 0;
	objects["Instance1"]["LineHeight"] = 1;
	objects["Instance1"]["Name"] = "Window";
	objects["Instance1"]["TextXAlignment"] = Enum.TextXAlignment.Center;
	objects["Instance1"]["Selectable"] = true;
	objects["Instance1"]["MaxVisibleGraphemes"] = -1;
	objects["Instance1"]["TextStrokeColor3"] = Color3.new(0, 0, 0);
	objects["Instance1"]["TextTransparency"] = 0;

	objects["Instance2"]["LayoutOrder"] = 0;
	objects["Instance2"]["Active"] = false;
	objects["Instance2"]["Parent"] = objects["Instance1"];
	objects["Instance2"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance2"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance2"]["ZIndex"] = 1;
	objects["Instance2"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance2"]["Size"] = UDim2.new(1, 0, 0, 30);
	objects["Instance2"]["Draggable"] = false;
	objects["Instance2"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance2"]["ClipsDescendants"] = true;
	objects["Instance2"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance2"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance2"]["BackgroundTransparency"] = 1;
	objects["Instance2"]["BorderSizePixel"] = 0;
	objects["Instance2"]["Rotation"] = 0;
	objects["Instance2"]["Transparency"] = 1;
	objects["Instance2"]["Name"] = "TopbarZone";
	objects["Instance2"]["SelectionOrder"] = 0;
	objects["Instance2"]["Visible"] = true;
	objects["Instance2"]["Selectable"] = false;
	objects["Instance2"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance2"]["BackgroundColor3"] = Color3.new(1, 1, 1);

	objects["Instance3"]["Visible"] = true;
	objects["Instance3"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance3"]["Size"] = UDim2.new(0.699999988079071, 0, 0.699999988079071, 0);
	objects["Instance3"]["ImageTransparency"] = 0;
	objects["Instance3"]["Parent"] = objects["Instance2"];
	objects["Instance3"]["Position"] = UDim2.new(0, 5, 0.4749999940395355, 0);
	objects["Instance3"]["BackgroundTransparency"] = 1;
	objects["Instance3"]["ImageRectOffset"] = Vector2.new(0, 0);
	objects["Instance3"]["AnchorPoint"] = Vector2.new(0, 0.5);
	objects["Instance3"]["Image"] = "rbxassetid://17245903072";
	objects["Instance3"]["TileSize"] = UDim2.new(1, 0, 1, 0);
	objects["Instance3"]["ImageRectSize"] = Vector2.new(0, 0);
	objects["Instance3"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance3"]["ZIndex"] = 1;
	objects["Instance3"]["BorderSizePixel"] = 0;
	objects["Instance3"]["SliceCenter"] = Rect.new(0, 0, 0, 0);
	objects["Instance3"]["Draggable"] = false;
	objects["Instance3"]["ScaleType"] = Enum.ScaleType.Stretch;
	objects["Instance3"]["ResampleMode"] = Enum.ResamplerMode.Default;
	objects["Instance3"]["ClipsDescendants"] = false;
	objects["Instance3"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance3"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance3"]["LayoutOrder"] = 0;
	objects["Instance3"]["ImageColor3"] = Color3.new(1, 1, 1);
	objects["Instance3"]["Rotation"] = 0;
	objects["Instance3"]["Transparency"] = 1;
	objects["Instance3"]["Name"] = "Icon";
	objects["Instance3"]["SelectionOrder"] = 0;
	objects["Instance3"]["SliceScale"] = 1;
	objects["Instance3"]["Selectable"] = false;
	objects["Instance3"]["Active"] = false;
	objects["Instance3"]["BackgroundColor3"] = Color3.new(1, 1, 1);

	objects["Instance4"]["AspectRatio"] = 1;
	objects["Instance4"]["Name"] = "UIAspectRatioConstraint";
	objects["Instance4"]["Parent"] = objects["Instance3"];
	objects["Instance4"]["AspectType"] = Enum.AspectType.FitWithinMaxSize;
	objects["Instance4"]["DominantAxis"] = Enum.DominantAxis.Width;

	objects["Instance5"]["Visible"] = true;
	objects["Instance5"]["FontSize"] = Enum.FontSize.Size14;
	objects["Instance5"]["TextDirection"] = Enum.TextDirection.Auto;
	objects["Instance5"]["Active"] = false;
	objects["Instance5"]["TextStrokeTransparency"] = 1;
	objects["Instance5"]["TextTruncate"] = Enum.TextTruncate.None;
	objects["Instance5"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance5"]["ZIndex"] = 1;
	objects["Instance5"]["BorderSizePixel"] = 0;
	objects["Instance5"]["Draggable"] = false;
	objects["Instance5"]["RichText"] = false;
	objects["Instance5"]["Transparency"] = 1;
	objects["Instance5"]["SelectionOrder"] = 0;
	objects["Instance5"]["TextYAlignment"] = Enum.TextYAlignment.Center;
	objects["Instance5"]["TextScaled"] = true;
	objects["Instance5"]["TextWrap"] = true;
	objects["Instance5"]["FontFace"] = Font.new("rbxasset://fonts/families/TitilliumWeb.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal, false);
	objects["Instance5"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance5"]["Parent"] = objects["Instance3"];
	objects["Instance5"]["AnchorPoint"] = Vector2.new(0, 0.5);
	objects["Instance5"]["TextSize"] = 14;
	objects["Instance5"]["Position"] = UDim2.new(1.5, 0, 0.5, 0);
	objects["Instance5"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance5"]["Size"] = UDim2.new(100, 0, 0.8999999761581421, 0);
	objects["Instance5"]["BackgroundTransparency"] = 1;
	objects["Instance5"]["LineHeight"] = 1;
	objects["Instance5"]["BackgroundColor3"] = Color3.new(1, 1, 1);
	objects["Instance5"]["TextColor3"] = Color3.new(1, 1, 1);
	objects["Instance5"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance5"]["Text"] = "Script.lua - Visual Studio Code";
	objects["Instance5"]["LayoutOrder"] = 0;
	objects["Instance5"]["TextWrapped"] = true;
	objects["Instance5"]["Rotation"] = 0;
	objects["Instance5"]["TextTransparency"] = 0;
	objects["Instance5"]["Name"] = "Title";
	objects["Instance5"]["TextXAlignment"] = Enum.TextXAlignment.Left;
	objects["Instance5"]["ClipsDescendants"] = false;
	objects["Instance5"]["MaxVisibleGraphemes"] = -1;
	objects["Instance5"]["TextStrokeColor3"] = Color3.new(0, 0, 0);
	objects["Instance5"]["Selectable"] = false;

	objects["Instance6"]["LayoutOrder"] = 0;
	objects["Instance6"]["Active"] = false;
	objects["Instance6"]["Parent"] = objects["Instance2"];
	objects["Instance6"]["AnchorPoint"] = Vector2.new(0, 1);
	objects["Instance6"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance6"]["ZIndex"] = 1;
	objects["Instance6"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance6"]["Size"] = UDim2.new(1, 0, 0, 1);
	objects["Instance6"]["Draggable"] = false;
	objects["Instance6"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance6"]["ClipsDescendants"] = false;
	objects["Instance6"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance6"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance6"]["BackgroundTransparency"] = 0;
	objects["Instance6"]["BorderSizePixel"] = 0;
	objects["Instance6"]["Rotation"] = 0;
	objects["Instance6"]["Transparency"] = 0;
	objects["Instance6"]["Name"] = "Separator";
	objects["Instance6"]["SelectionOrder"] = 0;
	objects["Instance6"]["Visible"] = true;
	objects["Instance6"]["Selectable"] = false;
	objects["Instance6"]["Position"] = UDim2.new(0, 0, 1, 0);
	objects["Instance6"]["BackgroundColor3"] = Color3.new(0.168627, 0.168627, 0.168627);

	objects["Instance7"]["LayoutOrder"] = 0;
	objects["Instance7"]["Active"] = false;
	objects["Instance7"]["Parent"] = objects["Instance2"];
	objects["Instance7"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance7"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance7"]["ZIndex"] = 1;
	objects["Instance7"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance7"]["Size"] = UDim2.new(1, 0, 1, -1);
	objects["Instance7"]["Draggable"] = false;
	objects["Instance7"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance7"]["ClipsDescendants"] = false;
	objects["Instance7"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance7"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance7"]["BackgroundTransparency"] = 1;
	objects["Instance7"]["BorderSizePixel"] = 0;
	objects["Instance7"]["Rotation"] = 0;
	objects["Instance7"]["Transparency"] = 1;
	objects["Instance7"]["Name"] = "Buttons";
	objects["Instance7"]["SelectionOrder"] = 0;
	objects["Instance7"]["Visible"] = true;
	objects["Instance7"]["Selectable"] = false;
	objects["Instance7"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance7"]["BackgroundColor3"] = Color3.new(1, 1, 1);

	objects["Instance8"]["FillDirection"] = Enum.FillDirection.Horizontal;
	objects["Instance8"]["HorizontalAlignment"] = Enum.HorizontalAlignment.Right;
	objects["Instance8"]["VerticalFlex"] = Enum.UIFlexAlignment.None;
	objects["Instance8"]["Parent"] = objects["Instance7"];
	objects["Instance8"]["VerticalAlignment"] = Enum.VerticalAlignment.Top;
	objects["Instance8"]["SortOrder"] = Enum.SortOrder.LayoutOrder;
	objects["Instance8"]["Name"] = "UIListLayout";
	objects["Instance8"]["Padding"] = UDim.new(0, 0);
	objects["Instance8"]["ItemLineAlignment"] = Enum.ItemLineAlignment.Automatic;
	objects["Instance8"]["HorizontalFlex"] = Enum.UIFlexAlignment.None;

	objects["Instance9"]["Visible"] = true;
	objects["Instance9"]["FontSize"] = Enum.FontSize.Size14;
	objects["Instance9"]["TextDirection"] = Enum.TextDirection.Auto;
	objects["Instance9"]["Active"] = true;
	objects["Instance9"]["TextStrokeTransparency"] = 1;
	objects["Instance9"]["TextTruncate"] = Enum.TextTruncate.None;
	objects["Instance9"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance9"]["ZIndex"] = 1;
	objects["Instance9"]["BorderSizePixel"] = 0;
	objects["Instance9"]["Draggable"] = false;
	objects["Instance9"]["RichText"] = false;
	objects["Instance9"]["Modal"] = false;
	objects["Instance9"]["AutoButtonColor"] = true;
	objects["Instance9"]["Transparency"] = 0;
	objects["Instance9"]["SelectionOrder"] = 0;
	objects["Instance9"]["TextYAlignment"] = Enum.TextYAlignment.Center;
	objects["Instance9"]["TextScaled"] = true;
	objects["Instance9"]["TextWrap"] = true;
	objects["Instance9"]["FontFace"] = Font.new("rbxasset://fonts/families/TitilliumWeb.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal, false);
	objects["Instance9"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance9"]["Parent"] = objects["Instance7"];
	objects["Instance9"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance9"]["Style"] = Enum.ButtonStyle.Custom;
	objects["Instance9"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance9"]["BackgroundColor3"] = Color3.new(0.117647, 0.117647, 0.117647);
	objects["Instance9"]["Selected"] = false;
	objects["Instance9"]["TextSize"] = 14;
	objects["Instance9"]["Size"] = UDim2.new(0, 40, 1, 0);
	objects["Instance9"]["BackgroundTransparency"] = 0;
	objects["Instance9"]["TextWrapped"] = true;
	objects["Instance9"]["ClipsDescendants"] = false;
	objects["Instance9"]["TextColor3"] = Color3.new(1, 1, 1);
	objects["Instance9"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance9"]["Text"] = "-";
	objects["Instance9"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance9"]["LayoutOrder"] = 0;
	objects["Instance9"]["Rotation"] = 0;
	objects["Instance9"]["LineHeight"] = 1;
	objects["Instance9"]["Name"] = "Minimize";
	objects["Instance9"]["TextXAlignment"] = Enum.TextXAlignment.Center;
	objects["Instance9"]["Selectable"] = true;
	objects["Instance9"]["MaxVisibleGraphemes"] = -1;
	objects["Instance9"]["TextStrokeColor3"] = Color3.new(0, 0, 0);
	objects["Instance9"]["TextTransparency"] = 0;

	objects["Instance10"]["PaddingTop"] = UDim.new(0, 0);
	objects["Instance10"]["Name"] = "UIPadding";
	objects["Instance10"]["Parent"] = objects["Instance9"];
	objects["Instance10"]["PaddingBottom"] = UDim.new(0.100000001, 0);
	objects["Instance10"]["PaddingLeft"] = UDim.new(0, 0);
	objects["Instance10"]["PaddingRight"] = UDim.new(0, 0);

	objects["Instance11"]["Visible"] = true;
	objects["Instance11"]["FontSize"] = Enum.FontSize.Size14;
	objects["Instance11"]["TextDirection"] = Enum.TextDirection.Auto;
	objects["Instance11"]["Active"] = true;
	objects["Instance11"]["TextStrokeTransparency"] = 1;
	objects["Instance11"]["TextTruncate"] = Enum.TextTruncate.None;
	objects["Instance11"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance11"]["ZIndex"] = 1;
	objects["Instance11"]["BorderSizePixel"] = 0;
	objects["Instance11"]["Draggable"] = false;
	objects["Instance11"]["RichText"] = false;
	objects["Instance11"]["Modal"] = false;
	objects["Instance11"]["AutoButtonColor"] = true;
	objects["Instance11"]["Transparency"] = 0;
	objects["Instance11"]["SelectionOrder"] = 0;
	objects["Instance11"]["TextYAlignment"] = Enum.TextYAlignment.Center;
	objects["Instance11"]["TextScaled"] = true;
	objects["Instance11"]["TextWrap"] = true;
	objects["Instance11"]["FontFace"] = Font.new("rbxasset://fonts/families/TitilliumWeb.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal, true);
	objects["Instance11"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance11"]["Parent"] = objects["Instance7"];
	objects["Instance11"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance11"]["Style"] = Enum.ButtonStyle.Custom;
	objects["Instance11"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance11"]["BackgroundColor3"] = Color3.new(0.117647, 0.117647, 0.117647);
	objects["Instance11"]["Selected"] = false;
	objects["Instance11"]["TextSize"] = 14;
	objects["Instance11"]["Size"] = UDim2.new(0, 40, 1, 0);
	objects["Instance11"]["BackgroundTransparency"] = 0;
	objects["Instance11"]["TextWrapped"] = true;
	objects["Instance11"]["ClipsDescendants"] = false;
	objects["Instance11"]["TextColor3"] = Color3.new(1, 1, 1);
	objects["Instance11"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance11"]["Text"] = "□";
	objects["Instance11"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance11"]["LayoutOrder"] = 0;
	objects["Instance11"]["Rotation"] = 0;
	objects["Instance11"]["LineHeight"] = 1;
	objects["Instance11"]["Name"] = "Maximize";
	objects["Instance11"]["TextXAlignment"] = Enum.TextXAlignment.Center;
	objects["Instance11"]["Selectable"] = true;
	objects["Instance11"]["MaxVisibleGraphemes"] = -1;
	objects["Instance11"]["TextStrokeColor3"] = Color3.new(0, 0, 0);
	objects["Instance11"]["TextTransparency"] = 0;

	objects["Instance12"]["PaddingTop"] = UDim.new(0.224999994, 0);
	objects["Instance12"]["Name"] = "UIPadding";
	objects["Instance12"]["Parent"] = objects["Instance11"];
	objects["Instance12"]["PaddingBottom"] = UDim.new(0.25, 0);
	objects["Instance12"]["PaddingLeft"] = UDim.new(0, 0);
	objects["Instance12"]["PaddingRight"] = UDim.new(0, 0);

	objects["Instance13"]["Visible"] = true;
	objects["Instance13"]["FontSize"] = Enum.FontSize.Size14;
	objects["Instance13"]["TextDirection"] = Enum.TextDirection.Auto;
	objects["Instance13"]["Active"] = true;
	objects["Instance13"]["TextStrokeTransparency"] = 1;
	objects["Instance13"]["TextTruncate"] = Enum.TextTruncate.None;
	objects["Instance13"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance13"]["ZIndex"] = 1;
	objects["Instance13"]["BorderSizePixel"] = 0;
	objects["Instance13"]["Draggable"] = false;
	objects["Instance13"]["RichText"] = false;
	objects["Instance13"]["Modal"] = false;
	objects["Instance13"]["AutoButtonColor"] = true;
	objects["Instance13"]["Transparency"] = 0;
	objects["Instance13"]["SelectionOrder"] = 0;
	objects["Instance13"]["TextYAlignment"] = Enum.TextYAlignment.Center;
	objects["Instance13"]["TextScaled"] = true;
	objects["Instance13"]["TextWrap"] = true;
	objects["Instance13"]["FontFace"] = Font.new("rbxasset://fonts/families/TitilliumWeb.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal, false);
	objects["Instance13"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance13"]["Parent"] = objects["Instance7"];
	objects["Instance13"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance13"]["Style"] = Enum.ButtonStyle.Custom;
	objects["Instance13"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance13"]["BackgroundColor3"] = Color3.new(0.117647, 0.117647, 0.117647);
	objects["Instance13"]["Selected"] = false;
	objects["Instance13"]["TextSize"] = 14;
	objects["Instance13"]["Size"] = UDim2.new(0, 40, 1, 0);
	objects["Instance13"]["BackgroundTransparency"] = 0;
	objects["Instance13"]["TextWrapped"] = true;
	objects["Instance13"]["ClipsDescendants"] = false;
	objects["Instance13"]["TextColor3"] = Color3.new(1, 1, 1);
	objects["Instance13"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance13"]["Text"] = "x";
	objects["Instance13"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance13"]["LayoutOrder"] = 0;
	objects["Instance13"]["Rotation"] = 0;
	objects["Instance13"]["LineHeight"] = 1;
	objects["Instance13"]["Name"] = "Close";
	objects["Instance13"]["TextXAlignment"] = Enum.TextXAlignment.Center;
	objects["Instance13"]["Selectable"] = true;
	objects["Instance13"]["MaxVisibleGraphemes"] = -1;
	objects["Instance13"]["TextStrokeColor3"] = Color3.new(0, 0, 0);
	objects["Instance13"]["TextTransparency"] = 0;

	objects["Instance14"]["PaddingTop"] = UDim.new(0, 0);
	objects["Instance14"]["Name"] = "UIPadding";
	objects["Instance14"]["Parent"] = objects["Instance13"];
	objects["Instance14"]["PaddingBottom"] = UDim.new(0.100000001, 0);
	objects["Instance14"]["PaddingLeft"] = UDim.new(0, 0);
	objects["Instance14"]["PaddingRight"] = UDim.new(0, 0);

	objects["Instance15"]["Enabled"] = true;
	objects["Instance15"]["Transparency"] = 0;
	objects["Instance15"]["Name"] = "UIStroke";
	objects["Instance15"]["LineJoinMode"] = Enum.LineJoinMode.Miter;
	objects["Instance15"]["Parent"] = objects["Instance1"];
	objects["Instance15"]["Thickness"] = 1;
	objects["Instance15"]["Color"] = Color3.new(0.0823529, 0.0823529, 0.0823529);
	objects["Instance15"]["ApplyStrokeMode"] = Enum.ApplyStrokeMode.Border;

	objects["Instance16"]["LayoutOrder"] = 0;
	objects["Instance16"]["Active"] = false;
	objects["Instance16"]["Parent"] = objects["Instance1"];
	objects["Instance16"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance16"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance16"]["ZIndex"] = 1;
	objects["Instance16"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance16"]["Size"] = UDim2.new(1, 0, 1, -30);
	objects["Instance16"]["Draggable"] = false;
	objects["Instance16"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance16"]["ClipsDescendants"] = false;
	objects["Instance16"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance16"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance16"]["BackgroundTransparency"] = 0;
	objects["Instance16"]["BorderSizePixel"] = 0;
	objects["Instance16"]["Rotation"] = 0;
	objects["Instance16"]["Transparency"] = 0;
	objects["Instance16"]["Name"] = "Contents";
	objects["Instance16"]["SelectionOrder"] = 0;
	objects["Instance16"]["Visible"] = true;
	objects["Instance16"]["Selectable"] = false;
	objects["Instance16"]["Position"] = UDim2.new(0, 0, 0, 30);
	objects["Instance16"]["BackgroundColor3"] = Color3.new(0.0941177, 0.0941177, 0.0941177);

	objects["Instance17"]["LayoutOrder"] = 0;
	objects["Instance17"]["Active"] = false;
	objects["Instance17"]["Parent"] = objects["Instance16"];
	objects["Instance17"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance17"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance17"]["ZIndex"] = 1;
	objects["Instance17"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance17"]["Size"] = UDim2.new(1, 0, 0, 35);
	objects["Instance17"]["Draggable"] = false;
	objects["Instance17"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance17"]["ClipsDescendants"] = false;
	objects["Instance17"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance17"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance17"]["BackgroundTransparency"] = 1;
	objects["Instance17"]["BorderSizePixel"] = 0;
	objects["Instance17"]["Rotation"] = 0;
	objects["Instance17"]["Transparency"] = 1;
	objects["Instance17"]["Name"] = "Top";
	objects["Instance17"]["SelectionOrder"] = 0;
	objects["Instance17"]["Visible"] = true;
	objects["Instance17"]["Selectable"] = false;
	objects["Instance17"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance17"]["BackgroundColor3"] = Color3.new(1, 1, 1);

	objects["Instance18"]["Visible"] = true;
	objects["Instance18"]["Active"] = true;
	objects["Instance18"]["ScrollingDirection"] = Enum.ScrollingDirection.XY;
	objects["Instance18"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance18"]["ZIndex"] = 2;
	objects["Instance18"]["BorderSizePixel"] = 0;
	objects["Instance18"]["CanvasSize"] = UDim2.new(0, 0, 0, 0);
	objects["Instance18"]["Draggable"] = false;
	objects["Instance18"]["MidImage"] = "rbxasset://textures/ui/Scroll/scroll-middle.png";
	objects["Instance18"]["CanvasPosition"] = Vector2.new(0, 0);
	objects["Instance18"]["VerticalScrollBarInset"] = Enum.ScrollBarInset.None;
	objects["Instance18"]["Transparency"] = 1;
	objects["Instance18"]["TopImage"] = "rbxasset://textures/ui/Scroll/scroll-top.png";
	objects["Instance18"]["SelectionOrder"] = 0;
	objects["Instance18"]["HorizontalScrollBarInset"] = Enum.ScrollBarInset.None;
	objects["Instance18"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance18"]["AutomaticCanvasSize"] = Enum.AutomaticSize.X;
	objects["Instance18"]["VerticalScrollBarPosition"] = Enum.VerticalScrollBarPosition.Right;
	objects["Instance18"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance18"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance18"]["Size"] = UDim2.new(1, -70, 1, 0);
	objects["Instance18"]["ScrollBarImageColor3"] = Color3.new(0, 0, 0);
	objects["Instance18"]["BackgroundColor3"] = Color3.new(1, 1, 1);
	objects["Instance18"]["Selectable"] = true;
	objects["Instance18"]["ClipsDescendants"] = true;
	objects["Instance18"]["ScrollBarImageTransparency"] = 0;
	objects["Instance18"]["ScrollBarThickness"] = 0;
	objects["Instance18"]["Parent"] = objects["Instance17"];
	objects["Instance18"]["BackgroundTransparency"] = 1;
	objects["Instance18"]["Rotation"] = 0;
	objects["Instance18"]["LayoutOrder"] = 0;
	objects["Instance18"]["Name"] = "Tabs";
	objects["Instance18"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance18"]["ScrollingEnabled"] = true;
	objects["Instance18"]["BottomImage"] = "rbxasset://textures/ui/Scroll/scroll-bottom.png";
	objects["Instance18"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance18"]["ElasticBehavior"] = Enum.ElasticBehavior.WhenScrollable;

	objects["Instance19"]["Visible"] = true;
	objects["Instance19"]["FontSize"] = Enum.FontSize.Size14;
	objects["Instance19"]["TextDirection"] = Enum.TextDirection.Auto;
	objects["Instance19"]["Active"] = true;
	objects["Instance19"]["TextStrokeTransparency"] = 1;
	objects["Instance19"]["TextTruncate"] = Enum.TextTruncate.None;
	objects["Instance19"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance19"]["ZIndex"] = 1;
	objects["Instance19"]["BorderSizePixel"] = 0;
	objects["Instance19"]["Draggable"] = false;
	objects["Instance19"]["RichText"] = false;
	objects["Instance19"]["Modal"] = false;
	objects["Instance19"]["AutoButtonColor"] = true;
	objects["Instance19"]["Transparency"] = 0;
	objects["Instance19"]["SelectionOrder"] = 0;
	objects["Instance19"]["TextYAlignment"] = Enum.TextYAlignment.Center;
	objects["Instance19"]["TextScaled"] = false;
	objects["Instance19"]["TextWrap"] = false;
	objects["Instance19"]["FontFace"] = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal, false);
	objects["Instance19"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance19"]["Parent"] = objects["Instance18"];
	objects["Instance19"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance19"]["Style"] = Enum.ButtonStyle.Custom;
	objects["Instance19"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance19"]["BackgroundColor3"] = Color3.new(0.121569, 0.121569, 0.121569);
	objects["Instance19"]["Selected"] = false;
	objects["Instance19"]["TextSize"] = 14;
	objects["Instance19"]["Size"] = UDim2.new(0, 150, 1, 0);
	objects["Instance19"]["BackgroundTransparency"] = 0;
	objects["Instance19"]["TextWrapped"] = false;
	objects["Instance19"]["ClipsDescendants"] = false;
	objects["Instance19"]["TextColor3"] = Color3.new(0, 0, 0);
	objects["Instance19"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance19"]["Text"] = "";
	objects["Instance19"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance19"]["LayoutOrder"] = 0;
	objects["Instance19"]["Rotation"] = 0;
	objects["Instance19"]["LineHeight"] = 1;
	objects["Instance19"]["Name"] = "Tab";
	objects["Instance19"]["TextXAlignment"] = Enum.TextXAlignment.Center;
	objects["Instance19"]["Selectable"] = true;
	objects["Instance19"]["MaxVisibleGraphemes"] = -1;
	objects["Instance19"]["TextStrokeColor3"] = Color3.new(0, 0, 0);
	objects["Instance19"]["TextTransparency"] = 0;

	objects["Instance20"]["LayoutOrder"] = 0;
	objects["Instance20"]["Active"] = false;
	objects["Instance20"]["Parent"] = objects["Instance19"];
	objects["Instance20"]["AnchorPoint"] = Vector2.new(1, 0);
	objects["Instance20"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance20"]["ZIndex"] = 1;
	objects["Instance20"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance20"]["Size"] = UDim2.new(0, 1, 1, 0);
	objects["Instance20"]["Draggable"] = false;
	objects["Instance20"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance20"]["ClipsDescendants"] = false;
	objects["Instance20"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance20"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance20"]["BackgroundTransparency"] = 0;
	objects["Instance20"]["BorderSizePixel"] = 0;
	objects["Instance20"]["Rotation"] = 0;
	objects["Instance20"]["Transparency"] = 0;
	objects["Instance20"]["Name"] = "LeftSeparator";
	objects["Instance20"]["SelectionOrder"] = 0;
	objects["Instance20"]["Visible"] = true;
	objects["Instance20"]["Selectable"] = false;
	objects["Instance20"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance20"]["BackgroundColor3"] = Color3.new(0.168627, 0.168627, 0.168627);

	objects["Instance21"]["LayoutOrder"] = 0;
	objects["Instance21"]["Active"] = false;
	objects["Instance21"]["Parent"] = objects["Instance19"];
	objects["Instance21"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance21"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance21"]["ZIndex"] = 1;
	objects["Instance21"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance21"]["Size"] = UDim2.new(1, -1, 0, 1);
	objects["Instance21"]["Draggable"] = false;
	objects["Instance21"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance21"]["ClipsDescendants"] = false;
	objects["Instance21"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance21"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance21"]["BackgroundTransparency"] = 0;
	objects["Instance21"]["BorderSizePixel"] = 0;
	objects["Instance21"]["Rotation"] = 0;
	objects["Instance21"]["Transparency"] = 0;
	objects["Instance21"]["Name"] = "Selected";
	objects["Instance21"]["SelectionOrder"] = 0;
	objects["Instance21"]["Visible"] = true;
	objects["Instance21"]["Selectable"] = false;
	objects["Instance21"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance21"]["BackgroundColor3"] = Color3.new(0, 0.470588, 0.984314);

	objects["Instance22"]["Visible"] = true;
	objects["Instance22"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance22"]["Size"] = UDim2.new(0.25, 0, 0.25, 0);
	objects["Instance22"]["ImageTransparency"] = 0;
	objects["Instance22"]["Parent"] = objects["Instance19"];
	objects["Instance22"]["Position"] = UDim2.new(0.10000000149011612, 0, 0.5, 0);
	objects["Instance22"]["BackgroundTransparency"] = 1;
	objects["Instance22"]["ImageRectOffset"] = Vector2.new(0, 0);
	objects["Instance22"]["AnchorPoint"] = Vector2.new(0.5, 0.5);
	objects["Instance22"]["Image"] = "rbxassetid://5552526748";
	objects["Instance22"]["TileSize"] = UDim2.new(1, 0, 1, 0);
	objects["Instance22"]["ImageRectSize"] = Vector2.new(0, 0);
	objects["Instance22"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance22"]["ZIndex"] = 1;
	objects["Instance22"]["BorderSizePixel"] = 0;
	objects["Instance22"]["SliceCenter"] = Rect.new(0, 0, 0, 0);
	objects["Instance22"]["Draggable"] = false;
	objects["Instance22"]["ScaleType"] = Enum.ScaleType.Stretch;
	objects["Instance22"]["ResampleMode"] = Enum.ResamplerMode.Default;
	objects["Instance22"]["ClipsDescendants"] = false;
	objects["Instance22"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance22"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance22"]["LayoutOrder"] = 0;
	objects["Instance22"]["ImageColor3"] = Color3.new(0, 0.470588, 0.984314);
	objects["Instance22"]["Rotation"] = 0;
	objects["Instance22"]["Transparency"] = 1;
	objects["Instance22"]["Name"] = "Icon";
	objects["Instance22"]["SelectionOrder"] = 0;
	objects["Instance22"]["SliceScale"] = 1;
	objects["Instance22"]["Selectable"] = false;
	objects["Instance22"]["Active"] = false;
	objects["Instance22"]["BackgroundColor3"] = Color3.new(1, 1, 1);

	objects["Instance23"]["AspectRatio"] = 1;
	objects["Instance23"]["Name"] = "UIAspectRatioConstraint";
	objects["Instance23"]["Parent"] = objects["Instance22"];
	objects["Instance23"]["AspectType"] = Enum.AspectType.FitWithinMaxSize;
	objects["Instance23"]["DominantAxis"] = Enum.DominantAxis.Width;

	objects["Instance24"]["LayoutOrder"] = 0;
	objects["Instance24"]["Active"] = false;
	objects["Instance24"]["Parent"] = objects["Instance19"];
	objects["Instance24"]["AnchorPoint"] = Vector2.new(1, 0);
	objects["Instance24"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance24"]["ZIndex"] = 1;
	objects["Instance24"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance24"]["Size"] = UDim2.new(0, 1, 1, 0);
	objects["Instance24"]["Draggable"] = false;
	objects["Instance24"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance24"]["ClipsDescendants"] = false;
	objects["Instance24"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance24"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance24"]["BackgroundTransparency"] = 0;
	objects["Instance24"]["BorderSizePixel"] = 0;
	objects["Instance24"]["Rotation"] = 0;
	objects["Instance24"]["Transparency"] = 0;
	objects["Instance24"]["Name"] = "RightSeparator";
	objects["Instance24"]["SelectionOrder"] = 0;
	objects["Instance24"]["Visible"] = true;
	objects["Instance24"]["Selectable"] = false;
	objects["Instance24"]["Position"] = UDim2.new(1, 0, 0, 0);
	objects["Instance24"]["BackgroundColor3"] = Color3.new(0.168627, 0.168627, 0.168627);

	objects["Instance25"]["LayoutOrder"] = 0;
	objects["Instance25"]["Active"] = false;
	objects["Instance25"]["Parent"] = objects["Instance19"];
	objects["Instance25"]["AnchorPoint"] = Vector2.new(0, 0.5);
	objects["Instance25"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance25"]["ZIndex"] = 1;
	objects["Instance25"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance25"]["Size"] = UDim2.new(0.550000011920929, 0, 0.5, 0);
	objects["Instance25"]["Draggable"] = false;
	objects["Instance25"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance25"]["ClipsDescendants"] = false;
	objects["Instance25"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance25"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance25"]["BackgroundTransparency"] = 1;
	objects["Instance25"]["BorderSizePixel"] = 0;
	objects["Instance25"]["Rotation"] = 0;
	objects["Instance25"]["Transparency"] = 1;
	objects["Instance25"]["Name"] = "NameHolder";
	objects["Instance25"]["SelectionOrder"] = 0;
	objects["Instance25"]["Visible"] = true;
	objects["Instance25"]["Selectable"] = false;
	objects["Instance25"]["Position"] = UDim2.new(0.20000000298023224, 0, 0.5, 0);
	objects["Instance25"]["BackgroundColor3"] = Color3.new(1, 1, 1);

	objects["Instance26"]["Visible"] = true;
	objects["Instance26"]["FontSize"] = Enum.FontSize.Size14;
	objects["Instance26"]["TextDirection"] = Enum.TextDirection.Auto;
	objects["Instance26"]["Active"] = false;
	objects["Instance26"]["TextStrokeTransparency"] = 1;
	objects["Instance26"]["TextTruncate"] = Enum.TextTruncate.None;
	objects["Instance26"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance26"]["ZIndex"] = 1;
	objects["Instance26"]["BorderSizePixel"] = 0;
	objects["Instance26"]["Draggable"] = false;
	objects["Instance26"]["RichText"] = false;
	objects["Instance26"]["Transparency"] = 1;
	objects["Instance26"]["SelectionOrder"] = 0;
	objects["Instance26"]["TextYAlignment"] = Enum.TextYAlignment.Center;
	objects["Instance26"]["TextScaled"] = true;
	objects["Instance26"]["TextWrap"] = true;
	objects["Instance26"]["FontFace"] = Font.new("rbxasset://fonts/families/TitilliumWeb.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal, false);
	objects["Instance26"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance26"]["Parent"] = objects["Instance25"];
	objects["Instance26"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance26"]["TextSize"] = 14;
	objects["Instance26"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance26"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance26"]["Size"] = UDim2.new(100, 0, 1, 0);
	objects["Instance26"]["BackgroundTransparency"] = 1;
	objects["Instance26"]["LineHeight"] = 1;
	objects["Instance26"]["BackgroundColor3"] = Color3.new(1, 1, 1);
	objects["Instance26"]["TextColor3"] = Color3.new(1, 1, 1);
	objects["Instance26"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance26"]["Text"] = "Script.lua";
	objects["Instance26"]["LayoutOrder"] = 0;
	objects["Instance26"]["TextWrapped"] = true;
	objects["Instance26"]["Rotation"] = 0;
	objects["Instance26"]["TextTransparency"] = 0;
	objects["Instance26"]["Name"] = "Label";
	objects["Instance26"]["TextXAlignment"] = Enum.TextXAlignment.Left;
	objects["Instance26"]["ClipsDescendants"] = false;
	objects["Instance26"]["MaxVisibleGraphemes"] = -1;
	objects["Instance26"]["TextStrokeColor3"] = Color3.new(0, 0, 0);
	objects["Instance26"]["Selectable"] = false;

	objects["Instance27"]["Visible"] = true;
	objects["Instance27"]["FontSize"] = Enum.FontSize.Size14;
	objects["Instance27"]["TextDirection"] = Enum.TextDirection.Auto;
	objects["Instance27"]["Active"] = true;
	objects["Instance27"]["TextStrokeTransparency"] = 1;
	objects["Instance27"]["TextTruncate"] = Enum.TextTruncate.None;
	objects["Instance27"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance27"]["ZIndex"] = 1;
	objects["Instance27"]["BorderSizePixel"] = 0;
	objects["Instance27"]["Draggable"] = false;
	objects["Instance27"]["RichText"] = false;
	objects["Instance27"]["Modal"] = false;
	objects["Instance27"]["AutoButtonColor"] = true;
	objects["Instance27"]["Transparency"] = 1;
	objects["Instance27"]["SelectionOrder"] = 0;
	objects["Instance27"]["TextYAlignment"] = Enum.TextYAlignment.Center;
	objects["Instance27"]["TextScaled"] = true;
	objects["Instance27"]["TextWrap"] = true;
	objects["Instance27"]["FontFace"] = Font.new("rbxasset://fonts/families/TitilliumWeb.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal, false);
	objects["Instance27"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance27"]["Parent"] = objects["Instance19"];
	objects["Instance27"]["AnchorPoint"] = Vector2.new(1, 0.5);
	objects["Instance27"]["Style"] = Enum.ButtonStyle.Custom;
	objects["Instance27"]["Position"] = UDim2.new(0.9750000238418579, 0, 0.5, 0);
	objects["Instance27"]["BackgroundColor3"] = Color3.new(1, 1, 1);
	objects["Instance27"]["Selected"] = false;
	objects["Instance27"]["TextSize"] = 14;
	objects["Instance27"]["Size"] = UDim2.new(0.75, 0, 0.75, 0);
	objects["Instance27"]["BackgroundTransparency"] = 1;
	objects["Instance27"]["TextWrapped"] = true;
	objects["Instance27"]["ClipsDescendants"] = false;
	objects["Instance27"]["TextColor3"] = Color3.new(1, 1, 1);
	objects["Instance27"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance27"]["Text"] = "x";
	objects["Instance27"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance27"]["LayoutOrder"] = 0;
	objects["Instance27"]["Rotation"] = 0;
	objects["Instance27"]["LineHeight"] = 1;
	objects["Instance27"]["Name"] = "Close";
	objects["Instance27"]["TextXAlignment"] = Enum.TextXAlignment.Center;
	objects["Instance27"]["Selectable"] = true;
	objects["Instance27"]["MaxVisibleGraphemes"] = -1;
	objects["Instance27"]["TextStrokeColor3"] = Color3.new(0, 0, 0);
	objects["Instance27"]["TextTransparency"] = 0;

	objects["Instance28"]["AspectRatio"] = 1;
	objects["Instance28"]["Name"] = "UIAspectRatioConstraint";
	objects["Instance28"]["Parent"] = objects["Instance27"];
	objects["Instance28"]["AspectType"] = Enum.AspectType.FitWithinMaxSize;
	objects["Instance28"]["DominantAxis"] = Enum.DominantAxis.Width;

	objects["Instance29"]["PaddingTop"] = UDim.new(0, 0);
	objects["Instance29"]["Name"] = "UIPadding";
	objects["Instance29"]["Parent"] = objects["Instance27"];
	objects["Instance29"]["PaddingBottom"] = UDim.new(0.100000001, 0);
	objects["Instance29"]["PaddingLeft"] = UDim.new(0, 0);
	objects["Instance29"]["PaddingRight"] = UDim.new(0, 0);

	objects["Instance30"]["FillDirection"] = Enum.FillDirection.Horizontal;
	objects["Instance30"]["HorizontalAlignment"] = Enum.HorizontalAlignment.Left;
	objects["Instance30"]["VerticalFlex"] = Enum.UIFlexAlignment.None;
	objects["Instance30"]["Parent"] = objects["Instance18"];
	objects["Instance30"]["VerticalAlignment"] = Enum.VerticalAlignment.Top;
	objects["Instance30"]["SortOrder"] = Enum.SortOrder.LayoutOrder;
	objects["Instance30"]["Name"] = "UIListLayout";
	objects["Instance30"]["Padding"] = UDim.new(0, 0);
	objects["Instance30"]["ItemLineAlignment"] = Enum.ItemLineAlignment.Automatic;
	objects["Instance30"]["HorizontalFlex"] = Enum.UIFlexAlignment.None;

	objects["Instance31"]["LayoutOrder"] = 0;
	objects["Instance31"]["Active"] = false;
	objects["Instance31"]["Parent"] = objects["Instance17"];
	objects["Instance31"]["AnchorPoint"] = Vector2.new(0, 1);
	objects["Instance31"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance31"]["ZIndex"] = 1;
	objects["Instance31"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance31"]["Size"] = UDim2.new(1, 0, 0, 1);
	objects["Instance31"]["Draggable"] = false;
	objects["Instance31"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance31"]["ClipsDescendants"] = false;
	objects["Instance31"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance31"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance31"]["BackgroundTransparency"] = 0;
	objects["Instance31"]["BorderSizePixel"] = 0;
	objects["Instance31"]["Rotation"] = 0;
	objects["Instance31"]["Transparency"] = 0;
	objects["Instance31"]["Name"] = "Separator";
	objects["Instance31"]["SelectionOrder"] = 0;
	objects["Instance31"]["Visible"] = true;
	objects["Instance31"]["Selectable"] = false;
	objects["Instance31"]["Position"] = UDim2.new(0, 0, 1, 0);
	objects["Instance31"]["BackgroundColor3"] = Color3.new(0.168627, 0.168627, 0.168627);

	objects["Instance32"]["LayoutOrder"] = 0;
	objects["Instance32"]["Active"] = false;
	objects["Instance32"]["Parent"] = objects["Instance17"];
	objects["Instance32"]["AnchorPoint"] = Vector2.new(1, 0);
	objects["Instance32"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance32"]["ZIndex"] = 1;
	objects["Instance32"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance32"]["Size"] = UDim2.new(0, 70, 1, -1);
	objects["Instance32"]["Draggable"] = false;
	objects["Instance32"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance32"]["ClipsDescendants"] = false;
	objects["Instance32"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance32"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance32"]["BackgroundTransparency"] = 1;
	objects["Instance32"]["BorderSizePixel"] = 0;
	objects["Instance32"]["Rotation"] = 0;
	objects["Instance32"]["Transparency"] = 1;
	objects["Instance32"]["Name"] = "Buttons";
	objects["Instance32"]["SelectionOrder"] = 0;
	objects["Instance32"]["Visible"] = true;
	objects["Instance32"]["Selectable"] = false;
	objects["Instance32"]["Position"] = UDim2.new(1, 0, 0, 0);
	objects["Instance32"]["BackgroundColor3"] = Color3.new(1, 1, 1);

	objects["Instance33"]["FillDirection"] = Enum.FillDirection.Horizontal;
	objects["Instance33"]["HorizontalAlignment"] = Enum.HorizontalAlignment.Right;
	objects["Instance33"]["VerticalFlex"] = Enum.UIFlexAlignment.None;
	objects["Instance33"]["Parent"] = objects["Instance32"];
	objects["Instance33"]["VerticalAlignment"] = Enum.VerticalAlignment.Top;
	objects["Instance33"]["SortOrder"] = Enum.SortOrder.LayoutOrder;
	objects["Instance33"]["Name"] = "UIListLayout";
	objects["Instance33"]["Padding"] = UDim.new(0, 0);
	objects["Instance33"]["ItemLineAlignment"] = Enum.ItemLineAlignment.Automatic;
	objects["Instance33"]["HorizontalFlex"] = Enum.UIFlexAlignment.None;

	objects["Instance34"]["Visible"] = true;
	objects["Instance34"]["FontSize"] = Enum.FontSize.Size14;
	objects["Instance34"]["TextDirection"] = Enum.TextDirection.Auto;
	objects["Instance34"]["Active"] = true;
	objects["Instance34"]["TextStrokeTransparency"] = 1;
	objects["Instance34"]["TextTruncate"] = Enum.TextTruncate.None;
	objects["Instance34"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance34"]["ZIndex"] = 1;
	objects["Instance34"]["BorderSizePixel"] = 0;
	objects["Instance34"]["Draggable"] = false;
	objects["Instance34"]["RichText"] = false;
	objects["Instance34"]["Modal"] = false;
	objects["Instance34"]["AutoButtonColor"] = true;
	objects["Instance34"]["Transparency"] = 0;
	objects["Instance34"]["SelectionOrder"] = 0;
	objects["Instance34"]["TextYAlignment"] = Enum.TextYAlignment.Center;
	objects["Instance34"]["TextScaled"] = false;
	objects["Instance34"]["TextWrap"] = false;
	objects["Instance34"]["FontFace"] = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal, false);
	objects["Instance34"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance34"]["Parent"] = objects["Instance32"];
	objects["Instance34"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance34"]["Style"] = Enum.ButtonStyle.Custom;
	objects["Instance34"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance34"]["BackgroundColor3"] = Color3.new(0.0941177, 0.0941177, 0.0941177);
	objects["Instance34"]["Selected"] = false;
	objects["Instance34"]["TextSize"] = 14;
	objects["Instance34"]["Size"] = UDim2.new(0.5, 0, 1, 0);
	objects["Instance34"]["BackgroundTransparency"] = 0;
	objects["Instance34"]["TextWrapped"] = false;
	objects["Instance34"]["ClipsDescendants"] = false;
	objects["Instance34"]["TextColor3"] = Color3.new(0, 0, 0);
	objects["Instance34"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance34"]["Text"] = "";
	objects["Instance34"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance34"]["LayoutOrder"] = 0;
	objects["Instance34"]["Rotation"] = 0;
	objects["Instance34"]["LineHeight"] = 1;
	objects["Instance34"]["Name"] = "Clear";
	objects["Instance34"]["TextXAlignment"] = Enum.TextXAlignment.Center;
	objects["Instance34"]["Selectable"] = true;
	objects["Instance34"]["MaxVisibleGraphemes"] = -1;
	objects["Instance34"]["TextStrokeColor3"] = Color3.new(0, 0, 0);
	objects["Instance34"]["TextTransparency"] = 0;

	objects["Instance35"]["Visible"] = true;
	objects["Instance35"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance35"]["Size"] = UDim2.new(0.6499999761581421, 0, 0.6499999761581421, 0);
	objects["Instance35"]["ImageTransparency"] = 0;
	objects["Instance35"]["Parent"] = objects["Instance34"];
	objects["Instance35"]["Position"] = UDim2.new(0.5, 0, 0.5, 0);
	objects["Instance35"]["BackgroundTransparency"] = 1;
	objects["Instance35"]["ImageRectOffset"] = Vector2.new(0, 0);
	objects["Instance35"]["AnchorPoint"] = Vector2.new(0.5, 0.5);
	objects["Instance35"]["Image"] = "rbxassetid://137784860208719";
	objects["Instance35"]["TileSize"] = UDim2.new(1, 0, 1, 0);
	objects["Instance35"]["ImageRectSize"] = Vector2.new(0, 0);
	objects["Instance35"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance35"]["ZIndex"] = 1;
	objects["Instance35"]["BorderSizePixel"] = 0;
	objects["Instance35"]["SliceCenter"] = Rect.new(0, 0, 0, 0);
	objects["Instance35"]["Draggable"] = false;
	objects["Instance35"]["ScaleType"] = Enum.ScaleType.Stretch;
	objects["Instance35"]["ResampleMode"] = Enum.ResamplerMode.Default;
	objects["Instance35"]["ClipsDescendants"] = false;
	objects["Instance35"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance35"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance35"]["LayoutOrder"] = 0;
	objects["Instance35"]["ImageColor3"] = Color3.new(1, 1, 1);
	objects["Instance35"]["Rotation"] = 90;
	objects["Instance35"]["Transparency"] = 1;
	objects["Instance35"]["Name"] = "ImageLabel";
	objects["Instance35"]["SelectionOrder"] = 0;
	objects["Instance35"]["SliceScale"] = 1;
	objects["Instance35"]["Selectable"] = false;
	objects["Instance35"]["Active"] = false;
	objects["Instance35"]["BackgroundColor3"] = Color3.new(1, 1, 1);

	objects["Instance36"]["Visible"] = true;
	objects["Instance36"]["FontSize"] = Enum.FontSize.Size14;
	objects["Instance36"]["TextDirection"] = Enum.TextDirection.Auto;
	objects["Instance36"]["Active"] = true;
	objects["Instance36"]["TextStrokeTransparency"] = 1;
	objects["Instance36"]["TextTruncate"] = Enum.TextTruncate.None;
	objects["Instance36"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance36"]["ZIndex"] = 1;
	objects["Instance36"]["BorderSizePixel"] = 0;
	objects["Instance36"]["Draggable"] = false;
	objects["Instance36"]["RichText"] = false;
	objects["Instance36"]["Modal"] = false;
	objects["Instance36"]["AutoButtonColor"] = true;
	objects["Instance36"]["Transparency"] = 0;
	objects["Instance36"]["SelectionOrder"] = 0;
	objects["Instance36"]["TextYAlignment"] = Enum.TextYAlignment.Center;
	objects["Instance36"]["TextScaled"] = false;
	objects["Instance36"]["TextWrap"] = false;
	objects["Instance36"]["FontFace"] = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal, false);
	objects["Instance36"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance36"]["Parent"] = objects["Instance32"];
	objects["Instance36"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance36"]["Style"] = Enum.ButtonStyle.Custom;
	objects["Instance36"]["Position"] = UDim2.new(0, 0, 0, 0);
	objects["Instance36"]["BackgroundColor3"] = Color3.new(0.0941177, 0.0941177, 0.0941177);
	objects["Instance36"]["Selected"] = false;
	objects["Instance36"]["TextSize"] = 14;
	objects["Instance36"]["Size"] = UDim2.new(0.5, 0, 1, 0);
	objects["Instance36"]["BackgroundTransparency"] = 0;
	objects["Instance36"]["TextWrapped"] = false;
	objects["Instance36"]["ClipsDescendants"] = false;
	objects["Instance36"]["TextColor3"] = Color3.new(0, 0, 0);
	objects["Instance36"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance36"]["Text"] = "";
	objects["Instance36"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance36"]["LayoutOrder"] = 0;
	objects["Instance36"]["Rotation"] = 0;
	objects["Instance36"]["LineHeight"] = 1;
	objects["Instance36"]["Name"] = "Execute";
	objects["Instance36"]["TextXAlignment"] = Enum.TextXAlignment.Center;
	objects["Instance36"]["Selectable"] = true;
	objects["Instance36"]["MaxVisibleGraphemes"] = -1;
	objects["Instance36"]["TextStrokeColor3"] = Color3.new(0, 0, 0);
	objects["Instance36"]["TextTransparency"] = 0;

	objects["Instance37"]["Visible"] = true;
	objects["Instance37"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance37"]["Size"] = UDim2.new(0.6499999761581421, 0, 0.6499999761581421, 0);
	objects["Instance37"]["ImageTransparency"] = 0;
	objects["Instance37"]["Parent"] = objects["Instance36"];
	objects["Instance37"]["Position"] = UDim2.new(0.5, 0, 0.5, 0);
	objects["Instance37"]["BackgroundTransparency"] = 1;
	objects["Instance37"]["ImageRectOffset"] = Vector2.new(0, 0);
	objects["Instance37"]["AnchorPoint"] = Vector2.new(0.5, 0.5);
	objects["Instance37"]["Image"] = "rbxassetid://7980684777";
	objects["Instance37"]["TileSize"] = UDim2.new(1, 0, 1, 0);
	objects["Instance37"]["ImageRectSize"] = Vector2.new(0, 0);
	objects["Instance37"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance37"]["ZIndex"] = 1;
	objects["Instance37"]["BorderSizePixel"] = 0;
	objects["Instance37"]["SliceCenter"] = Rect.new(0, 0, 0, 0);
	objects["Instance37"]["Draggable"] = false;
	objects["Instance37"]["ScaleType"] = Enum.ScaleType.Stretch;
	objects["Instance37"]["ResampleMode"] = Enum.ResamplerMode.Default;
	objects["Instance37"]["ClipsDescendants"] = false;
	objects["Instance37"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance37"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance37"]["LayoutOrder"] = 0;
	objects["Instance37"]["ImageColor3"] = Color3.new(1, 1, 1);
	objects["Instance37"]["Rotation"] = 90;
	objects["Instance37"]["Transparency"] = 1;
	objects["Instance37"]["Name"] = "ImageLabel";
	objects["Instance37"]["SelectionOrder"] = 0;
	objects["Instance37"]["SliceScale"] = 1;
	objects["Instance37"]["Selectable"] = false;
	objects["Instance37"]["Active"] = false;
	objects["Instance37"]["BackgroundColor3"] = Color3.new(1, 1, 1);

	objects["Instance38"]["LayoutOrder"] = 0;
	objects["Instance38"]["FontSize"] = Enum.FontSize.Size14;
	objects["Instance38"]["LineHeight"] = 1;
	objects["Instance38"]["Active"] = true;
	objects["Instance38"]["TextStrokeTransparency"] = 1;
	objects["Instance38"]["SelectionStart"] = -1;
	objects["Instance38"]["PlaceholderColor3"] = Color3.new(0.7, 0.7, 0.7);
	objects["Instance38"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance38"]["ZIndex"] = 1;
	objects["Instance38"]["BorderSizePixel"] = 0;
	objects["Instance38"]["TextEditable"] = true;
	objects["Instance38"]["Draggable"] = false;
	objects["Instance38"]["RichText"] = false;
	objects["Instance38"]["Transparency"] = 0;
	objects["Instance38"]["SelectionOrder"] = 0;
	objects["Instance38"]["TextYAlignment"] = Enum.TextYAlignment.Center;
	objects["Instance38"]["TextScaled"] = false;
	objects["Instance38"]["BackgroundColor3"] = Color3.new(0.121569, 0.121569, 0.121569);
	objects["Instance38"]["FontFace"] = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal, false);
	objects["Instance38"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance38"]["Parent"] = objects["Instance16"];
	objects["Instance38"]["TextWrapped"] = false;
	objects["Instance38"]["MaxVisibleGraphemes"] = -1;
	objects["Instance38"]["Name"] = "CodeEditor";
	objects["Instance38"]["AnchorPoint"] = Vector2.new(0, 0);
	objects["Instance38"]["TextTransparency"] = 0;
	objects["Instance38"]["TextDirection"] = Enum.TextDirection.Auto;
	objects["Instance38"]["CursorPosition"] = 1;
	objects["Instance38"]["ClipsDescendants"] = false;
	objects["Instance38"]["PlaceholderText"] = "";
	objects["Instance38"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance38"]["Size"] = UDim2.new(1, 0, 1, -35);
	objects["Instance38"]["TextStrokeColor3"] = Color3.new(0, 0, 0);
	objects["Instance38"]["Selectable"] = true;
	objects["Instance38"]["ShowNativeInput"] = true;
	objects["Instance38"]["TextColor3"] = Color3.new(0, 0, 0);
	objects["Instance38"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance38"]["Text"] = "TextBox";
	objects["Instance38"]["TextSize"] = 14;
	objects["Instance38"]["Visible"] = true;
	objects["Instance38"]["Rotation"] = 0;
	objects["Instance38"]["MultiLine"] = false;
	objects["Instance38"]["BackgroundTransparency"] = 0;
	objects["Instance38"]["TextXAlignment"] = Enum.TextXAlignment.Center;
	objects["Instance38"]["TextTruncate"] = Enum.TextTruncate.None;
	objects["Instance38"]["ClearTextOnFocus"] = true;
	objects["Instance38"]["Position"] = UDim2.new(0, 0, 0, 35);
	objects["Instance38"]["TextWrap"] = false;

	objects["Instance39"]["LayoutOrder"] = 0;
	objects["Instance39"]["Active"] = false;
	objects["Instance39"]["Parent"] = objects["Instance1"];
	objects["Instance39"]["AnchorPoint"] = Vector2.new(1, 0);
	objects["Instance39"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance39"]["ZIndex"] = 1;
	objects["Instance39"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance39"]["Size"] = UDim2.new(0, 150, 1, -30);
	objects["Instance39"]["Draggable"] = false;
	objects["Instance39"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance39"]["ClipsDescendants"] = false;
	objects["Instance39"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance39"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance39"]["BackgroundTransparency"] = 0;
	objects["Instance39"]["BorderSizePixel"] = 0;
	objects["Instance39"]["Rotation"] = 0;
	objects["Instance39"]["Transparency"] = 0;
	objects["Instance39"]["Name"] = "Scripts";
	objects["Instance39"]["SelectionOrder"] = 0;
	objects["Instance39"]["Visible"] = true;
	objects["Instance39"]["Selectable"] = false;
	objects["Instance39"]["Position"] = UDim2.new(0, 0, 0, 30);
	objects["Instance39"]["BackgroundColor3"] = Color3.new(0.0941177, 0.0941177, 0.0941177);

	objects["Instance40"]["LayoutOrder"] = 0;
	objects["Instance40"]["Active"] = false;
	objects["Instance40"]["Parent"] = objects["Instance39"];
	objects["Instance40"]["AnchorPoint"] = Vector2.new(1, 0);
	objects["Instance40"]["SizeConstraint"] = Enum.SizeConstraint.RelativeXY;
	objects["Instance40"]["ZIndex"] = 1;
	objects["Instance40"]["AutomaticSize"] = Enum.AutomaticSize.None;
	objects["Instance40"]["Size"] = UDim2.new(0, 1, 1, 0);
	objects["Instance40"]["Draggable"] = false;
	objects["Instance40"]["Style"] = Enum.FrameStyle.Custom;
	objects["Instance40"]["ClipsDescendants"] = false;
	objects["Instance40"]["BorderColor3"] = Color3.new(0, 0, 0);
	objects["Instance40"]["BorderMode"] = Enum.BorderMode.Outline;
	objects["Instance40"]["BackgroundTransparency"] = 0;
	objects["Instance40"]["BorderSizePixel"] = 0;
	objects["Instance40"]["Rotation"] = 0;
	objects["Instance40"]["Transparency"] = 0;
	objects["Instance40"]["Name"] = "Separator";
	objects["Instance40"]["SelectionOrder"] = 0;
	objects["Instance40"]["Visible"] = true;
	objects["Instance40"]["Selectable"] = false;
	objects["Instance40"]["Position"] = UDim2.new(1, 0, 0, 0);
	objects["Instance40"]["BackgroundColor3"] = Color3.new(0.168627, 0.168627, 0.168627);

	objects["Instance41"]["AspectRatio"] = 1.7999999523162842;
	objects["Instance41"]["Name"] = "UIAspectRatioConstraint";
	objects["Instance41"]["Parent"] = objects["Instance1"];
	objects["Instance41"]["AspectType"] = Enum.AspectType.FitWithinMaxSize;
	objects["Instance41"]["DominantAxis"] = Enum.DominantAxis.Width;

	objects["Instance42"]["Parent"] = objects["Instance1"];
	objects["Instance42"]["Name"] = "Editor";
	objects["Instance42"]["Enabled"] = true;
end;

-- Set scripts
do
	task.spawn(function() -- Instance42
		if not game:GetService("RunService"):IsClient() then return end
		local script = objects["Instance42"];
		-- lazy code blepphhh :P

		local syntaxColors = {
			Text = Color3.fromRGB(212, 212, 212),
			Background = Color3.fromRGB(31, 31, 31),
			Selection = Color3.fromRGB(200, 200, 255),
			SelectionBack = Color3.fromRGB(45, 50, 65),
			Operator = Color3.fromRGB(212, 212, 212),
			Number = Color3.fromRGB(181, 206, 168),
			String = Color3.fromRGB(206, 145, 120),
			Comment = Color3.fromRGB(106, 153, 85),
			Keyword = Color3.fromRGB(170, 104, 176),
			Error = Color3.fromRGB(255, 0, 0),
			FindBackground = Color3.fromRGB(255, 190, 110),
			MatchingWord = Color3.fromRGB(100, 80, 100),
			BuiltIn = Color3.fromRGB(142, 220, 254),
			CurrentLine = Color3.fromRGB(45, 45, 45),
			LocalMethod = Color3.fromRGB(220, 220, 170),
			LocalProperty = Color3.fromRGB(158, 220, 254),
			Nil = Color3.fromRGB(86, 156, 214),
			Bool = Color3.fromRGB(86, 156, 214),
			Function = Color3.fromRGB(170, 104, 176),
			Local = Color3.fromRGB(86, 156, 214),
			Self = Color3.fromRGB(86, 156, 214),
			FunctionName = Color3.fromRGB(220, 220, 170),
			Bracket = Color3.fromRGB(255, 220, 22),

			Transparency = 0,
			Font = Enum.Font.Code,
			WidthDivider = 2
		}

		local size = game:GetService("UserInputService").KeyboardEnabled and UDim2.fromScale(0.5, 0.5) or UDim2.fromScale(0.8, 0.8)

		script.Parent.Visible = false
		script.Parent.Parent.Parent = getfenv().gethui and getfenv().gethui() or game:GetService("CoreGui") or game:GetService("Players").LocalPlayer.PlayerGui
		script.Parent.Size = size

		local codeBox = script:FindFirstChild("CodeBox") and require(script.CodeBox) or loadstring(game:HttpGet("https://raw.githubusercontent.com/InfernusScripts/Null-Fire/main/Core/Libraries/CodeBox/Main.lua"))()
		local textBox = codeBox:fromTextBox(script.Parent.Contents.CodeEditor, syntaxColors)

		script.Parent.Visible = true

		local delta, dragInput
		local function makeDraggable(gui, xOnly, minX, maxX)
			minX = tonumber(minX) or -math.huge
			maxX = tonumber(maxX) or  math.huge

			local dragging, dragStart, startPos, delta

			gui.InputBegan:Connect(function(input)
				if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
					dragging = true
					dragStart = input.Position
					startPos = gui.Position

					input.Changed:Connect(function()
						if input.UserInputState == Enum.UserInputState.End then
							dragging = false
						end
					end)
				end
			end)

			gui.InputChanged:Connect(function(input)
				if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
					dragInput = input
				end
			end)

			game:GetService("UserInputService").InputChanged:Connect(function(input)
				if input == dragInput and dragging then
					delta = input.Position - dragStart
					gui:TweenPosition(UDim2.new(startPos.X.Scale, math.clamp(startPos.X.Offset + delta.X, minX, maxX), not xOnly and startPos.Y.Scale or 0, not xOnly and startPos.Y.Offset + delta.Y or 0), nil, nil, 0.3, true)
					delta = nil
				end
			end)
		end

		makeDraggable(script.Parent)

		local execute = script.Parent.Contents.Top.Buttons.Execute
		execute.Visible = pcall(loadstring, "print('yo')")
		execute.MouseButton1Click:Connect(function()
			local func, err = loadstring(textBox.Text)
			if func then
				func()
			else
				warn(err)
			end
		end)

		execute.Parent.Clear.MouseButton1Click:Connect(function()
			textBox.Text = ""
		end)

		local maximized = false
		script.Parent.Changed:Connect(function()
			if maximized then
				script.Parent.Position = UDim2.fromScale(0.5, 0.5)
			end
		end)

		local close = script.Parent.TopbarZone.Buttons.Close
		close.MouseButton1Click:Connect(function()
			script.Parent:Destroy()
		end)

		local ratio = script.Parent.UIAspectRatioConstraint
		close.Parent.Maximize.MouseButton1Click:Connect(function()
			maximized = not maximized

			script.Parent.Size = UDim2.fromOffset(script.Parent.AbsoluteSize.X, script.Parent.AbsoluteSize.Y)
			script.Parent:TweenSize(maximized and UDim2.fromScale(1, 1) or size, Enum.EasingDirection.Out, Enum.EasingStyle.Quint, 0.35, true)

			ratio.Parent = not maximized and script.Parent or nil
		end)
	end);
end;
